-- Keymaps are automatically loaded on the VeryLazy event
-- Default keymaps that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/keymaps.lua
-- Add any additional keymaps here
--

vim.keymap.set("n", "<leader>fs", require("telescope.builtin").lsp_document_symbols) -- Run REST query
-- vim.keymap.set("n", "<leader>xr", ":call VrcQuery()<CR>") -- Run REST query
--
-- -- vim.keymap.set("n", "<leader>oo", ":ObsidianFollowLink <CR>")
-- -- vim.keymap.set("n", "<leader>of", "<cmd>ObsidianQuickSwitch <CR>")
-- --
--
-- local opts = { noremap = true, silent = false }
--
-- -- Create a new note after asking for its title.
-- vim.api.nvim_set_keymap("n", "<leader>zn", "<Cmd>ZkNew { title = vim.fn.input('Title: ') }<CR>", opts)
--
-- -- Open notes.
-- vim.api.nvim_set_keymap("n", "<leader>zo", "<Cmd>ZkNotes { sort = { 'modified' } }<CR>", opts)
-- -- Open notes associated with the selected tags.
-- vim.api.nvim_set_keymap("n", "<leader>zt", "<Cmd>ZkTags<CR>", opts)
--
-- -- Search for the notes matching a given query.
-- vim.api.nvim_set_keymap(
--   "n",
--   "<leader>zf",
--   "<Cmd>ZkNotes { sort = { 'modified' }, match = { vim.fn.input('Search: ') } }<CR>",
--   opts
-- )
-- -- Search for the notes matching the current visual selection.
-- vim.api.nvim_set_keymap("v", "<leader>zf", ":'<,'>ZkMatch<CR>", opts)
